name: 工作流例子
run-name: ${{ github.actor }} 正在测试 GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      phone:
        description: '选择手机型号：'
        required: true
        default: '小米10'
        type: choice
        options:
          - 小米10
          - 小米10pro
      susfs:
        description: '是否集成SUSFS'
        required: true
        type: boolean
      version:
        description: '自定义版本名（如perf-xxx）/可为空（则为n0kernel）'
        required: false
        type: string
jobs:
  test_job:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
      MODEL: ${{ inputs.phone == '小米10' && 'Mi10' || 'MI10PRO' }} 
    steps:
      - run: echo "🎉 该任务自动触发于 ${{ github.event_name }} 事件."
      - run: echo "🐧 这个任务现在运行于系统 ${{ runner.os }} 的服务主机在Github!"
      - run: echo "🔎 你现在的分支为 ${{ github.ref }} 和你的仓库是 ${{ github.repository }}."
      - name: 检查仓库代码
        uses: actions/checkout@v4
      - run: echo "💡 这个 ${{ github.repository }} 仓库已经被克隆到runner."
      - run: echo "🖥️ 该工作流现在已经准备好在runner上测试代码"
      
      - name: 检出仓库脚本到运行器
        uses: actions/checkout@v4  
      - name: 授予 x 权限
        run: chmod +x ./hello.sh
      - name: 运行该脚本
        run: ./hello.sh

      - name: 输出环境变量
        run: |
          echo $MODEL
      
      - name: 输出输入框内容
        run: |
          echo "手机机型为 ${{ inputs.phone }} "
          echo "是否集成susfs ${{ inputs.susfs }} "
          echo "自定义版本号为 ${{ inputs.version }} "
          
      - name: 判断一些输入框内容
        run: |    
          if [ $MODEL = Mi10 ]; then
            echo "选择小米10配置的补丁"
            echo "defconfig=vendor/umi_defconfig" >> $GITHUB_ENV
          fi

          if [ $MODEL = MI10PRO ]; then
            echo "选择小米10配置的补丁"
            echo "defconfig=vendor/cmi_defconfig" >> $GITHUB_ENV
          fi

          echo "当前配置文件为"
          echo $defconfig
      
      # - name: 查看成果
      #   run: |
      #       dd if=/dev/zero of=Image bs=1M count=1
      #       cp Image ./Anykernel/

      # - name: '上传刷入包'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: KSUN_SUS_Mi10.zip
      #     path: ./Anykernel/*
      #     retention-days: 2

